//! The boot splash: the Anastasia mark as a halftone dot field, with a light
//! sweep crossing it diagonally, over the window while the app settles.
//!
//! Ported from Zeron (<https://github.com/zeronsh/comet>, MIT).
//!
//! This is a boot *beat*, not a progress indicator. Waku loads its state
//! synchronously before the first frame, so there is no connect phase to cover
//! and nothing to wait on — the overlay holds for a fixed moment, then lifts.
//! It never blocks input, and reduce-motion skips it outright: a decorative
//! animation must not delay someone who asked for less of them.

use std::time::Duration;

use gpui::{
    AnimationExt, AnyElement, ElementId, IntoElement, SharedString, Styled, div, prelude::*, px,
};

use crate::theme::Theme;
use crate::ui::motion::{self, SPLASH_IN, SPLASH_OUT};

/// How long the mark holds before it starts lifting. Half the sweep period, so
/// the light crosses the mark once and the app is not kept waiting on an
/// animation it has no reason to finish.
pub const SPLASH_HOLD: Duration = Duration::from_millis(1100);

/// Grid pitch and dot geometry. The pitch sets the mark's footprint
/// (46 × 8 ≈ 368px square) — comfortably inside even a narrow window.
const DOT_PITCH: f32 = 8.0;
/// The largest a dot grows, as a fraction of the pitch. Below 1.0 so even a
/// solid cell keeps the gap that makes the field read as a halftone.
const DOT_MAX: f32 = 0.72;
/// Fraction of the sweep cycle the light occupies as it crosses the diagonal.
const SWEEP_SPREAD: f32 = 0.55;
/// Rest opacity of a solid cell; the sweep lifts it to full.
const DOT_DIM: f32 = 0.28;
/// How many cells in from each edge the field fades out over. Stands in for
/// the radial mask — this gpui fork has no per-primitive edge fade, so the
/// ramp is baked into each cell's opacity instead.
const FADE_CELLS: f32 = 6.0;

/// The mark's halftone grid, generated by `scripts/halftone.py` from the logo:
/// one digit per cell, `0` (empty) to `9` (solid), sampled from ink coverage.
/// Regenerate it whenever the logo changes.
const HERO_DOTS: &str = include_str!("../../assets/hero-dots.txt");

/// Which part of its life the splash is in.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SplashPhase {
    Visible,
    FadingOut,
    Gone,
}

/// Intensity of the sweep at cycle position `t`, resting at `dim` and briefly
/// rising to full — a slow decay with a quick return, so the light reads as
/// travelling rather than throbbing.
fn sweep_opacity(t: f32, dim: f32) -> f32 {
    let t = t.rem_euclid(1.0);
    if t < 0.45 {
        motion::lerp(1.0, dim, t / 0.45)
    } else if t < 0.92 {
        dim
    } else {
        motion::lerp(dim, 1.0, (t - 0.92) / 0.08)
    }
}

/// How much of the field survives at `(x, y)`: 1.0 in the middle, ramping to
/// 0 within [`FADE_CELLS`] of any edge.
fn edge_falloff(x: usize, y: usize, columns: usize, rows: usize) -> f32 {
    let distance = [
        x as f32,
        y as f32,
        (columns.saturating_sub(1) - x.min(columns.saturating_sub(1))) as f32,
        (rows.saturating_sub(1) - y.min(rows.saturating_sub(1))) as f32,
    ]
    .into_iter()
    .fold(f32::MAX, f32::min);
    (distance / FADE_CELLS).clamp(0.0, 1.0)
}

/// The mark as a halftone dot field. Cell density drives both dot diameter and
/// opacity, so the glyph's edges dissolve into the surrounding field instead of
/// ending on a staircase, and the dim background cells stay visible as the
/// field the mark sits in.
///
/// ponytail: 46×46 = 2116 elements, rebuilt at the pulse clock's ~30fps for
/// about a second at launch. Halve the grid in `halftone.py` if it ever shows
/// up in a frame budget.
fn hero_dots(theme: &Theme) -> AnyElement {
    let color = theme.text;
    let rows: Vec<&str> = HERO_DOTS.lines().filter(|line| !line.is_empty()).collect();
    let row_count = rows.len();
    let column_count = rows.first().map_or(0, |row| row.len());
    let span = (row_count + column_count) as f32;

    motion::pulse(SPLASH_IN.total(), move |phase| {
        div()
            .flex()
            .flex_col()
            .children(rows.iter().enumerate().map(|(y, line)| {
                div()
                    .flex()
                    .flex_row()
                    .children(line.bytes().enumerate().map(move |(x, cell)| {
                        // Ink coverage, 0.0..=1.0.
                        let ink = f32::from(cell.saturating_sub(b'0').min(9)) / 9.0;
                        // The sweep leads at the top-left and trails at the
                        // bottom-right, so the light crosses on the diagonal.
                        let offset = (x + y) as f32 / span * SWEEP_SPREAD;
                        let dot = DOT_PITCH * DOT_MAX * ink;
                        let opacity = ink
                            * sweep_opacity(phase + offset, DOT_DIM)
                            * edge_falloff(x, y, column_count, row_count);
                        div()
                            .size(px(DOT_PITCH))
                            .flex()
                            .items_center()
                            .justify_center()
                            .child(
                                div()
                                    .size(px(dot))
                                    .rounded(px(dot / 2.0))
                                    .bg(color)
                                    .opacity(opacity),
                            )
                    }))
            }))
            .into_any_element()
    })
    .into_any_element()
}

/// The word under the mark. gpui has no letter-spacing at the pinned revision,
/// so the tracking is approximated with thin spaces.
fn loading_word(theme: &Theme) -> impl IntoElement {
    div()
        .text_size(px(11.0))
        .text_color(theme.text_tertiary)
        .child(SharedString::from(
            "L\u{2009}O\u{2009}A\u{2009}D\u{2009}I\u{2009}N\u{2009}G",
        ))
}

/// The overlay itself. Painted above the app but claiming no input, so a click
/// during boot lands on what it looks like it landed on.
pub fn splash_overlay(theme: &Theme, phase: SplashPhase) -> Option<AnyElement> {
    if phase == SplashPhase::Gone {
        return None;
    }
    let content = div()
        .absolute()
        .inset_0()
        .bg(theme.surface)
        .flex()
        .flex_col()
        .items_center()
        .justify_center()
        .gap(px(28.0))
        .child(hero_dots(theme))
        .child(loading_word(theme));

    Some(match phase {
        SplashPhase::Visible => content.into_any_element(),
        // A stable element id keeps gpui's animation clock from restarting:
        // it keys the start time by the element-id path, so a re-render with
        // the same id continues rather than replaying.
        SplashPhase::FadingOut => content
            .with_animation(
                ElementId::from("boot-splash-out"),
                SPLASH_OUT.animation(),
                |element, delta| element.opacity(1.0 - delta).top(px(-6.0 * delta)),
            )
            .into_any_element(),
        SplashPhase::Gone => unreachable!("returned above"),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_grid_is_square_and_carries_signal() {
        let rows: Vec<&str> = HERO_DOTS.lines().filter(|line| !line.is_empty()).collect();
        assert!(!rows.is_empty());
        assert!(
            rows.iter().all(|row| row.len() == rows.len()),
            "the sweep's diagonal assumes a square grid"
        );
        assert!(
            rows.iter()
                .flat_map(|row| row.bytes())
                .all(|c| c.is_ascii_digit()),
            "every cell is one 0-9 ink level"
        );
        // The mark has to actually be in there: some cell is at full ink.
        assert!(rows.iter().any(|row| row.contains('9')));
    }

    #[test]
    fn the_sweep_rests_dim_and_peaks_at_full() {
        // Start of the cycle: the light is on this cell.
        assert_eq!(sweep_opacity(0.0, DOT_DIM), 1.0);
        // Mid-cycle: resting.
        assert_eq!(sweep_opacity(0.7, DOT_DIM), DOT_DIM);
        // The cycle closes back at full, so it loops without a seam.
        assert!((sweep_opacity(0.999, DOT_DIM) - 1.0).abs() < 0.02);
        // Phase wraps, so a cell's offset can push it past 1.0 safely.
        assert_eq!(sweep_opacity(1.7, DOT_DIM), sweep_opacity(0.7, DOT_DIM));
        assert_eq!(sweep_opacity(2.0, DOT_DIM), sweep_opacity(0.0, DOT_DIM));
    }

    #[test]
    fn the_field_fades_out_at_every_edge() {
        // Corners and edges vanish.
        assert_eq!(edge_falloff(0, 0, 46, 46), 0.0);
        assert_eq!(edge_falloff(45, 45, 46, 46), 0.0);
        assert_eq!(edge_falloff(0, 20, 46, 46), 0.0);
        assert_eq!(edge_falloff(20, 45, 46, 46), 0.0);
        // The middle is untouched.
        assert_eq!(edge_falloff(23, 23, 46, 46), 1.0);
        // And the ramp in between is partial.
        let ramp = edge_falloff(3, 23, 46, 46);
        assert!(ramp > 0.0 && ramp < 1.0, "{ramp}");
    }
}
